python btch.py 0 \
python btch.py 1 \
python btch.py 2 \
python btch.py 3 \
python btch.py 4 \
python btch.py 5 \
python btch.py 6 \
python btch.py 7 \
python btch.py 8 \
python btch.py 9 \
python btch.py 10 \
python btch.py 11 \
python btch.py 12 \
python btch.py 13 \
python btch.py 14 \
python btch.py 15 \
python btch.py 16 &
